version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  cypress:
    build: 
      context: testing/cypress
      dockerfile: Dockerfile-cypress
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/trial-promoter-app
    ports:
      - "3000:3000"
    depends_on:
      - db
