require 'csv'

class DataReportGenerator
  def self.generate_report(messages)
    CSV.open("tcors_data_report.csv", "wb", :write_headers => true, :headers => ['stem', 'fda_campaign', 'theme', 'lin_meth_factor', 'lin_meth_level', 'variant', 'sm_type', 'day_experiment', 'date_sent', 'day_sent', 'time_sent', 'medium', 'image_included', 'total_clicks_day_1', 'total_clicks_day_2', 'total_clicks_day_3', 'total_clicks_experiment', 'click_time', 'total_impressions_day_1', 'total_impressions_day_2', 'total_impressions_day_3', 'total_impressions_experiment', 'retweet_twitter', 'share_facebook', 'share_instagram', 'reply_twitter', 'comment_facebook', 'comment_instagram', 'likes_twitter', 'likes_facebook', 'likes_instagram', 'total_sessions_day_1', 'total_sessions_day_2', 'total_sessions_day_3', 'total_sessions_experiment', 'sessions', 'clicks', 'users', 'exits', 'session_duration', 'time_on_page', 'pageviews']) do |csv|
      messages.each do |message|
        csv << [TcorsDataReportMapper.stem(message), TcorsDataReportMapper.fda_campaign(message), TcorsDataReportMapper.theme(message), TcorsDataReportMapper.lin_meth_factor(message), TcorsDataReportMapper.lin_meth_level(message), TcorsDataReportMapper.variant(message), TcorsDataReportMapper.sm_type(message), TcorsDataReportMapper.day_experiment(message), TcorsDataReportMapper.date_sent(message), TcorsDataReportMapper.day_sent(message), TcorsDataReportMapper.time_sent(message), TcorsDataReportMapper.medium(message), TcorsDataReportMapper.image_included(message), TcorsDataReportMapper.total_clicks_day_1(message), TcorsDataReportMapper.total_clicks_day_2(message), TcorsDataReportMapper.total_clicks_day_3(message), TcorsDataReportMapper.total_clicks_experiment(message), TcorsDataReportMapper.click_time(message), TcorsDataReportMapper.total_impressions_day_1(message), TcorsDataReportMapper.total_impressions_day_2(message), TcorsDataReportMapper.total_impressions_day_3(message), TcorsDataReportMapper.total_impressions_experiment(message), TcorsDataReportMapper.retweet_twitter(message), TcorsDataReportMapper.share_facebook(message), TcorsDataReportMapper.share_instagram(message), TcorsDataReportMapper.reply_twitter(message), TcorsDataReportMapper.comment_facebook(message), TcorsDataReportMapper.comment_instagram(message), TcorsDataReportMapper.likes_twitter(message), TcorsDataReportMapper.likes_facebook(message), TcorsDataReportMapper.likes_instagram(message), TcorsDataReportMapper.total_sessions_day_1(message), TcorsDataReportMapper.total_sessions_day_2(message), TcorsDataReportMapper.total_sessions_day_3(message), TcorsDataReportMapper.total_sessions_experiment(message), TcorsDataReportMapper.sessions(message), TcorsDataReportMapper.clicks(message), TcorsDataReportMapper.users(message), TcorsDataReportMapper.exits(message), TcorsDataReportMapper.session_duration(message), TcorsDataReportMapper.time_on_page(message), TcorsDataReportMapper.pageviews(message)]
      end
    end
  end
end