# config/app.yml for rails-settings-cached
defaults: &defaults
  buffer_access_token: ""
  enable_data_sharing: true
  google_auth_json_file: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
