# config/app.yml for rails-settings-cached
defaults: &defaults
  buffer_access_token: ""
  enable_data_sharing: true
  twitter_consumer_key: ""
  twitter_consumer_secret: ""
  twitter_access_token: ""
  twitter_access_token_secret: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
