# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d62e601dfb34d27fba000384b782f58d2b8c689717db869cf6ab6413b4f20656800ad4d80d61bfa4a535da200bd2e6b88c5d847f195f29f031d279c85100e23d
  TWITTER_KEY: 'eUOykFoUNflW3TmbzAZRZipew'
  TWITTER_SECRET: 'vsBe3pf67BNm8R3PBbGwon6WlTvSAPjUlxXIuRtDkPTQhGWrvh'
test:
  secret_key_base: e0843105f17b53faba074e8a924ac2f709db67afc9f6d57124762abe0e3cd7b4578397d2bef7338300787e749ea1dd50c1de4cc716ffce9b8e7328f800718632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  TWITTER_KEY: <%= ENV["TWITTER_KEY"] %>
  TWITTER_SECRET: <%= ENV["TWITTER_SECRET"] %>
